1. Generate n by n symmetric matrix, where each non diagonal element follow Poisson distribution and diagonal element is 0.
2. 

In [10]:
# Package
import numpy as np
from itertools import permutations

In [7]:
# Parameters
n = 8
lam = 2

In [ ]:
# Functions

## Generate Matrix
def get_mat(size, pois_lambda):
    dist_mat = np.zeros(shape = (size,size))
    for i in range(size):
        for j in range(i+1, size):
            dist_mat[i,j] = np.random.poisson(pois_lambda)
            dist_mat[j,i] = dist_mat[i,j]
    return dist_mat

## 4-points condition check function
def four_points_cond(mat):
    perm_lists = permutations(range(n), r = 4)
    for p in perm_lists:
        xy = mat[p[0], p[1]]
        zt = mat[p[2], p[3]]
        
        xz = mat[p[0], p[2]]
        yt = mat[p[1], p[2]]

        xt = mat[p[0], p[3]]
        yz = mat[p[1], p[2]]

        if xy+zt > max(xz+yt, xt+yz):
            return False
    return True

In [32]:
mat = get_mat(size = n, pois_lambda = lam)
it_max = pow(10, 6)

for it in range(it_max):
    if four_points_cond(mat) == False:
        mat = get_mat(size = n, pois_lambda = lam)
    else:
        break
    if it == it_max - 1:
        print("Can't Generate!!")



Can't Generate!!


In [33]:
print(mat, four_points_cond(mat))

[[0. 4. 2. 6. 1. 1. 3. 1.]
 [4. 0. 1. 3. 0. 1. 1. 3.]
 [2. 1. 0. 3. 4. 2. 3. 2.]
 [6. 3. 3. 0. 1. 1. 2. 2.]
 [1. 0. 4. 1. 0. 1. 5. 1.]
 [1. 1. 2. 1. 1. 0. 1. 4.]
 [3. 1. 3. 2. 5. 1. 0. 1.]
 [1. 3. 2. 2. 1. 4. 1. 0.]] False


In [35]:
it_max = pow(10, 7)
cnt = 0
for it in range(it_max):
    mat = get_mat(size = n, pois_lambda = lam)
    if four_points_cond(mat) == True:
        cnt = cnt + 1
    
print(cnt / it_max)


0.0
